### PR TITLE
Update to API V3

### PR DESCRIPTION
**Pull request by trey-jones**
All tests are passing, though I haven't scrutinized the response data that much - it looks good at a glance.     I tried to keep the API mostly the same, as much as the updated response fields allowed.  Let me know if you have any concerns.  I might extend this, depending on my own needs.  Seemed like a good starting point.  Thanks for it!

### CODE REVIEW

**Comment by DannyBen** [comment]
Looks good at first glance, excellent work! 
I would like to pull and test locally a little later before merging in.

**Comment by DannyBen** [comment]
Hey - I have opened branch [apiv3](https://github.com/DannyBen/quandl/compare/apiv3?expand=1), merged your changes, and did some formatting and linting.

I think we better handle the `// TODO` variables in the response types before merging to master. Will take a look tomorrow,

**Comment by trey-jones** [comment]
Good call - almost forgot.  Those were meant to make sure I checked that
the types were ok.

**Comment by trey-jones** [comment]
I went ahead and removed the TODO - they are numbers as expected, and type should be int.  I arbitrarily used `uint` for IDs and page counts - this may not be correct.

**Comment by DannyBen** [comment]
Merged, after updating another forgotten TODO in the examples.

Thanks :+1:

**Pull request merged**
